name: Build
on:
  push:
    branches:
      - main
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: ${{github.repository}} # defaults to current repo
          keep_latest: 0
          delete_tags: true
          delete_tag_pattern: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}